title: Yanan Wu (吴亚楠)
position: Ph.D Student in Computer Science
affiliation: Beijing Jiaotong University,<br> No.3 Shangyuancun, Haidian District,<br> Beijing China
email: ynwu0510@bjtu.edu.cn <br> ynw0510@gmail.com 
email_link: mailto:ynw0510@gmail.com
github_link: https://github.com/yananwu0510
weixin: ./assets/img/weixin.png
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
